// Firestore-shaped mentor docs (path: mentors/{mentorId}) — swap source later, keep shape.
export const mockMentors = [
  {
    id: 'mentor_001',
    uid: 'user_mentor_001',
    name: 'Marcus Chen',
    firm: 'Goldman Sachs',
    role: 'Investment Banking Analyst',
    track: 'Investment Banking',
    bio: 'Coverage analyst focused on IB recruiting and superday prep.',
    tags: ['Superday Prep', 'IB Recruiting'],
    sessionTypes: ['coaching', 'mock_interview', 'resume_review'],
    pricePerSession: 200,
    rating: 4.9,
    totalSessions: 47,
    available: true,
  },
  {
    id: 'mentor_002',
    uid: 'user_mentor_002',
    name: 'Priya Nair',
    firm: 'McKinsey & Company',
    role: 'Associate',
    track: 'Management Consulting',
    bio: 'Case interview coaching and fit prep for MBB pipelines.',
    tags: ['Case Prep', 'MBB'],
    sessionTypes: ['coaching', 'mock_interview'],
    pricePerSession: 250,
    rating: 5.0,
    totalSessions: 63,
    available: true,
  },
  {
    id: 'mentor_003',
    uid: 'user_mentor_003',
    name: 'Jordan Wells',
    firm: 'Meta',
    role: 'Senior Software Engineer',
    track: 'Tech & FAANG',
    bio: 'System design and interview loops for senior IC tracks.',
    tags: ['System Design', 'LeetCode'],
    sessionTypes: ['coaching', 'mock_interview'],
    pricePerSession: 175,
    rating: 4.8,
    totalSessions: 38,
    available: true,
  },
  {
    id: 'mentor_004',
    uid: 'user_mentor_004',
    name: 'Sofia Reyes',
    firm: 'KKR',
    role: 'PE Associate',
    track: 'Private Equity',
    bio: 'On-cycle PE prep, modeling, and recruiting strategy.',
    tags: ['LBO', 'PE Recruiting'],
    sessionTypes: ['coaching', 'resume_review'],
    pricePerSession: 300,
    rating: 4.9,
    totalSessions: 29,
    available: true,
  },
]
